# general settings
name: DSEC_IE_MVSRecur
model_type: MVSRecurModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DSECMVS
    type: DSECMVSRecurDataset
    dataset_path: /data/xhchen10/DSEC
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 10000
    prefetch_mode: ~

  val:
    name: DSECMVS
    type: DSECMVSRecurDataset
    dataset_path: /data/xhchen10/DSEC
    num_worker_per_gpu: 2
    io_backend:
      type: disk

# network structures
network_g:
  type: MVSRecurNet
  max_disp: 95

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000,100000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  loss_disp:
    type: SubpixelCrossEntropy

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false
  metrics:
    epe: # metric name, can be arbitrary
      type: compute_absolute_error
      better: lower
    3pe:
      type: compute_n_pixels_error
      n: 3
      better: lower
    2pe:
      type: compute_n_pixels_error
      n: 2
      better: lower
    1pe:
      type: compute_n_pixels_error
      n: 1
      better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
